### ISSUE TITLE
assert가 exception 다른 점은?(김수민)

### ISSUE THREAD

**Issue by kssumin** [JNU-econovation/Javs#65]
## 문제가 무엇인가?
```
assert 조건식
assert 조건식: AssertionError메세지

assert false;
Exception in thread "main" java.lang.AssertionError
	at test.Main.main(Main.java:23)

assert false: "단언문 실패 메세지입니다.";
// 발생 Exception
Exception in thread "main" java.lang.AssertionError: 단언문 실패 메세지입니다.
	at test.Main.main(Main.java:23)
```

## 왜 이런 문제를 선정하였는가?
assert문을 사용하는 경우는 언제일까?
exception으로 예외처리를 하는데 assert는 왜 따로 존재하는 것일까?

## 자신이 생각한 답변은 무엇인가?
`예외` 

- 잘못된 입력 데이터를 검사
- 발생할 것으로 예상되는 조건에는 예외를 사용

`어셜션` 

- 설계 시 가정한 내용이 실제로 유효한지 확인하기 위한 검증 용도
- 프로그램 내부의 논리 검사
- 코드의 버그를 검사

실제 프로젝트에서는 절대 발생해서는 안 되는 조건을 예외로 처리하여 어설션이 참이 되도록 한다.
[Exception Vs Assertion](https://stackoverflow.com/questions/1276308/exception-vs-assertion)

책에 나왔던 예시로 생각을 해본다면
사용자 로부터 받는 값을 0보다 커야 한다.

이때 사용자로부터 받는 값은 0보다 커야 한다.(exception)
0보다 큰 값을 나누었을 때도 0보다 큰 값이 나와야 한다(assert)로 처리할 수 있을 것같다.

즉 코드가 프로그래머가 예상한 대로 돌아가는지 체크

```java
public class Test {

	/**
	 * (mod m)값을 반환한다. 이 메서드는
	 * 항상 음이 아닌 BigInteger를 반환한다는 점에서 reminder 메서드와 다르다.
	 * 
	 * @param m 계수(양수어야 한다.)
	 * @return 현재 값 mod m
	 * @throws ArithmeticException m이 0보다 작으면 발생한다.
	 */
	public BigInteger mod(BigInteger m){
		if(m.signum()<=0){
			throw new ArithmeticException("계수(m)은 양수여야 합니다. "+m);
		}
		/**
		 * 계산 수행
		 */
	}
}
```

**Comment by BlackBean99** [comment]
설명 미쳤다 박영규클린 자바 그 잡채

**Comment by kssumin** [comment]
data 자체가 잘못 : exception
data를 가지고 프로그래머가 잘못되게 프로그램을 짬 : assert
